#write or choice your name file of your langs
serverlang: fr_FR
#write your nameIs
is:
  1:
    name: "Island1"
    #name your folder id in /islandList/
    folderName: "void"
  2:
    name: "Island2"
    #name your folder id in /islandList/
    folderName: "void1"

#Ã©crire le niveau des iles , et combien ils peuvent avoir comme bonus
islandLevelConfig:
  0:
    home_max: 1
    bank_max: 20000
  1:
    home_max: 2
    bank_max: 50000